# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the Gradle Daemon.
# Setting a larger heap size for the daemon helps avoid OutOfMemoryError during builds.
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
org.gradle.parallel=true

# Enables the use of AndroidX for the project
android.useAndroidX=true
# Automatically converts third-party libraries to use AndroidX
android.enableJetifier=true

# Increase memory for Kotlin daemon
kotlin.daemon.jvmargs=-Xmx2g
